# ========== Confirm Menu by MaximePremont ==========

# List of orders that require confirmation
Commands: "stop, reload"

# Messages and sounds
ConfirmMessage: "&eAre you sure ?"
OpenSound: true

# [Do not touch ] Configuration version
ConfigVersion: 1.0.1#en