# ========== Confirm Menu by MaximePremont ==========

# List of orders that require confirmation
Commands: "stop, reload"

# Enable open sound
OpenSound: true

# Messages ( color codes are valid )
Text:
    ConfirmMessage: "&eAre you sure ?"
    MenuTitle: "&8&lCONFIRM"
    MenuConfirm: "&a&lCONFIRM"
    MenuCancel: "&c&lCANCEL"

# [Do not touch ] Configuration version
ConfigVersion: 1.0.2#en