# ========== Confirm Menu by MaximePremont ==========

# List of commands that require a confirmation with menu
Commands: "reload, stop"
# List of commands that require a confirmation by writing "confirm"
CommandsWrite: "kick, ban"

# Enable open sound
OpenSound: true
# OP players have permission to skip confirmation by default ( confirmmenu.skip )
SkipPermsForOP : false
# Messages ( color codes are valid )
Text:
    ConfirmMessage: "&eAre you sure ?"
    WriteConfirmMessage: "&eWrite CONFIRM to confirm, or something else to cancel."
    CancelMessage: "&cCanceled !"
    MenuTitle: "&8&lCONFIRM"
    MenuConfirm: "&a&lCONFIRM"
    MenuCancel: "&c&lCANCEL"
    NewVersion: "&eA new version of the plugin is available !"
    UpdateFail: "&cCould not check for updates !"
# Changing the language will automatically change the configuration on the next reboot
# Available languages : EN | FR | ES | OTHER
Language : "EN"
# Check for updates and send a message to the console
UpdateCheck: true

# [Do not touch ] Configuration version
ConfigVersion: 1.0.8#en